### ISSUE TITLE
Executing over CPU

### ISSUE THREAD

**Issue by surajpadhy** [lancopku/WEAN#4]
Hello,

In list of parameters i see only GPU option, is there any way to train the model using CPU?
My laptop has only Intel's inbuild graphics memory available (Graphics: Intel® Kabylake GT1.5). 
Getting error:

RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:32
[INFO/MainProcess] process shutting down

How do i use it?
Any assistance is highly appreciated.

**Comment by danitamm** [comment]
Hi surajpadhy,

I fixed this by setting the parser argument -gpu to -1. My understanding is that torch.cuda.set_device(-1) sets the cuda device to be the cpu.

**Comment by superwoou** [comment]
how about to set gpu parameter to -1?

**Comment by gdgovinddaga6** [comment]
Add any negative integer value in the args.
Eg: python3 run.py -gpu -2 -mode evaluate -restore save_path/best.th
